export interface Recipe {
  slug: string
  title: string
  intro: string
  youtubeId: string
  time: string
  serves: string
  ingredients: string[]
  steps: string[]
  loop: string
  poster: string
}

export const recipes: Recipe[] = [
  {
    slug: 'makhana-bhel',
    title: 'Makhana Bhel Recipe',
    intro:
      'A lighter, crunchier twist on Mumbai\'s iconic street food. Golden Deer classic-roast makhana replaces fried puri for a bhel that\'s every bit as tangy and chaat-filled, but with half the oil and twice the crunch. Perfect for evening chaat cravings without the post-snack heaviness.',
    youtubeId: 'REPLACE_WITH_REAL_VIDEO_ID',
    time: '10 minutes',
    serves: '2',
    ingredients: [
      '2 cups Golden Deer Classic Roast makhana',
      '1 medium onion, finely chopped',
      '1 medium tomato, finely chopped',
      '½ cup boiled potato, diced',
      '¼ cup fresh pomegranate arils',
      '2 tbsp green chutney',
      '2 tbsp sweet tamarind chutney',
      '½ tsp chaat masala',
      '¼ tsp red chilli powder',
      'Sev (nylon or bhujia) for garnish',
      'Fresh coriander leaves',
      'Lemon juice to taste',
      'Salt to taste',
    ],
    steps: [
      'In a large mixing bowl, gently crush the Golden Deer Classic Roast makhana with your hands into bite-sized pieces — aim for halves and quarters, not powder.',
      'Add the chopped onion, tomato, boiled potato, and pomegranate arils.',
      'Drizzle green chutney and sweet tamarind chutney over the mixture. Toss gently with a spatula — don\'t overmix or the makhana will lose its crunch.',
      'Sprinkle chaat masala, red chilli powder, and a pinch of salt. Squeeze fresh lemon juice over everything.',
      'Transfer to serving bowls immediately. Top with a generous handful of sev and fresh coriander leaves.',
      'Serve right away — bhel waits for no one. The makhana stays crunchy for about 10–15 minutes after assembling.',
    ],
    loop: '/videos/recipes/makhana-bhel.mp4',
    poster: '/videos/recipes/makhana-bhel-poster.jpg',
  },
  {
    slug: 'makhana-kheer',
    title: 'Makhana Kheer Recipe',
    intro:
      'A royal Indian dessert made wholesome. Makhana kheer is a beloved festive treat across North India — roasted fox nuts simmered in sweetened milk until they soften into silky, pearl-like dumplings. Our version uses Golden Deer raw makhana for the most authentic texture, with cardamom and saffron for that heirloom touch.',
    youtubeId: 'REPLACE_WITH_REAL_VIDEO_ID',
    time: '35 minutes',
    serves: '4',
    ingredients: [
      '1 cup Golden Deer Premium Raw Makhana',
      '1 litre full-fat milk',
      '¼ cup sugar (or jaggery powder for a deeper flavour)',
      '2 tbsp ghee',
      '8–10 saffron strands soaked in 2 tbsp warm milk',
      '½ tsp cardamom powder',
      '2 tbsp chopped almonds',
      '2 tbsp chopped pistachios',
      '1 tbsp raisins',
      'A handful of slivered pistachios for garnish',
    ],
    steps: [
      'Heat ghee in a heavy-bottomed pan over medium heat. Add raw makhana and roast for 4–5 minutes, stirring constantly, until they become crisp and golden. Set aside to cool slightly, then roughly crush half of them.',
      'In the same pan, bring milk to a gentle boil. Reduce heat to low and let it simmer, stirring occasionally to prevent scorching.',
      'Add the crushed and whole roasted makhana to the simmering milk. Cook for 15–18 minutes, stirring every few minutes, until the makhana soften and absorb the milk — they should feel like soft dumplings.',
      'Add sugar (or jaggery), saffron milk, and cardamom powder. Stir well and cook for another 5 minutes until the kheer thickens to your preferred consistency.',
      'Add chopped almonds, pistachios, and raisins. Cook for 2 more minutes.',
      'Remove from heat. The kheer will thicken further as it cools. Garnish with slivered pistachios and a few saffron strands.',
      'Serve warm in winter, chilled in summer. The makhana pearls should be tender but still hold their shape.',
    ],
    loop: '/videos/recipes/makhana-kheer.mp4',
    poster: '/videos/recipes/makhana-kheer-poster.jpg',
  },
  {
    slug: 'peri-peri-makhana',
    title: 'Peri Peri Makhana Recipe',
    intro:
      'The cult favourite peri-peri flavour, now on India\'s cleanest crunch. This DIY version lets you control the heat while avoiding the MSG and artificial colouring of packaged peri-peri snacks. The secret is smoked paprika + fresh bird\'s eye chilli — smoky, fierce, and utterly addictive.',
    youtubeId: 'REPLACE_WITH_REAL_VIDEO_ID',
    time: '15 minutes',
    serves: '2',
    ingredients: [
      '2 cups Golden Deer Classic Roast makhana',
      '2 tbsp olive oil or cold-pressed sunflower oil',
      '1 tsp smoked paprika',
      '½ tsp Kashmiri red chilli powder (for deep colour)',
      '1–2 fresh bird\'s eye chillies, finely minced',
      '½ tsp garlic powder',
      '½ tsp onion powder',
      '½ tsp dried oregano',
      '¼ tsp lemon zest',
      'Salt to taste',
      'Fresh lemon wedges for serving',
    ],
    steps: [
      'Preheat oven to 160°C or a heavy pan over medium-low heat.',
      'In a small bowl, whisk together oil, smoked paprika, chilli powder, minced bird\'s eye chilli, garlic powder, onion powder, oregano, lemon zest, and salt to form a spiced oil paste.',
      'Place Golden Deer makhana in a large bowl. Pour the spiced oil over them and toss thoroughly, ensuring every piece is coated. Use your hands to massage the paste into the crevices.',
      'Spread the coated makhana in a single layer on a baking tray lined with parchment. Bake for 8–10 minutes, tossing halfway, until the coating is dry and the makhana are fragrant.',
      'If using a pan: dry-roast on medium-low for 5–6 minutes, stirring constantly to avoid burning the paprika.',
      'Let cool completely — the crunch intensifies as they cool. Serve with lemon wedges to squeeze just before eating.',
      'Store in an airtight container for up to 5 days (if they last that long).',
    ],
    loop: '/videos/recipes/peri-peri-makhana.mp4',
    poster: '/videos/recipes/peri-peri-makhana-poster.jpg',
  },
  {
    slug: 'makhana-chaat',
    title: 'Makhana Chaat Recipe',
    intro:
      'Every Indian household needs a five-minute chaat recipe that hits all the right notes — sweet, tangy, spicy, crunchy. This makhana chaat delivers exactly that, using yoghurt and chutneys as a creamy counterpoint to the airy crunch of Golden Deer makhana. Street-food energy, clean-label conscience.',
    youtubeId: 'REPLACE_WITH_REAL_VIDEO_ID',
    time: '5 minutes',
    serves: '2',
    ingredients: [
      '2 cups Golden Deer Classic Roast makhana',
      '½ cup thick curd (Greek yoghurt works best)',
      '2 tbsp sweet tamarind chutney',
      '1 tbsp green chutney',
      '¼ cup finely chopped onion',
      '¼ cup finely chopped tomato',
      '2 tbsp fresh pomegranate arils',
      '1 tbsp roasted cumin powder',
      '½ tsp chaat masala',
      '¼ tsp Kashmiri red chilli powder',
      '2 tbsp finely chopped coriander',
      '2 tbsp nylon sev for garnish',
      'Salt to taste',
    ],
    steps: [
      'Spread Golden Deer Classic Roast makhana on a wide serving plate in a single layer.',
      'Whisk the curd with a pinch of salt and cumin powder until smooth. Dot spoonfuls of curd across the makhana — don\'t drown them, you want some dry crunch remaining.',
      'Drizzle sweet tamarind chutney and green chutney in a crisscross pattern over the curd.',
      'Scatter chopped onion, tomato, and pomegranate arils evenly over the top.',
      'Sprinkle chaat masala, red chilli powder, and remaining cumin powder.',
      'Garnish generously with fresh coriander and nylon sev.',
      'Serve immediately with a spoon — each bite should get some curd, some chutney, and plenty of crunchy makhana.',
    ],
    loop: '/videos/recipes/makhana-chaat.mp4',
    poster: '/videos/recipes/makhana-chaat-poster.jpg',
  },
  {
    slug: 'golden-trail-mix',
    title: 'Golden Trail Mix Recipe',
    intro:
      'The ultimate energy snack for hikers, desk-workers, and anyone who needs sustained energy without a sugar crash. Golden Deer Classic Roast makhana forms the crunchy base, joined by nuts, seeds, dried fruit, and a whisper of dark chocolate. No baking required — just toss and go.',
    youtubeId: 'REPLACE_WITH_REAL_VIDEO_ID',
    time: '5 minutes',
    serves: 'Makes about 4 cups',
    ingredients: [
      '1½ cups Golden Deer Classic Roast makhana',
      '½ cup raw almonds',
      '½ cup raw walnuts, roughly broken',
      '¼ cup pumpkin seeds',
      '¼ cup sunflower seeds',
      '½ cup dried cranberries or goji berries',
      '¼ cup golden raisins',
      '2 tbsp dark chocolate chips (70%+ cacao)',
      '½ tsp cinnamon powder',
      '¼ tsp sea salt flakes',
      '1 tbsp maple syrup or honey (optional, for a sweetened version)',
    ],
    steps: [
      'In a large mixing bowl, combine Golden Deer makhana, almonds, walnuts, pumpkin seeds, and sunflower seeds.',
      'If making the sweetened version: warm the maple syrup slightly, toss with the nut-makhana mix, and spread on a baking tray. Bake at 140°C for 8 minutes, then let cool completely for a crunchy praline effect. If unsweetened, skip this step.',
      'Add dried cranberries, golden raisins, and dark chocolate chips to the cooled mix.',
      'Sprinkle cinnamon powder and sea salt flakes. Toss everything gently with your hands — the chocolate chips will soften slightly from the warmth of the nuts but should mostly stay intact.',
      'Store in an airtight jar at room temperature for up to 2 weeks. It will never last that long.',
      'Portion into small bags for on-the-go snacking, or keep a big jar on your desk for mid-afternoon cravings.',
    ],
    loop: '/videos/recipes/golden-trail-mix.mp4',
    poster: '/videos/recipes/golden-trail-mix-poster.jpg',
  },
  {
    slug: 'makhana-curry',
    title: 'Makhana Curry Recipe',
    intro:
      'A creamy, aromatic North Indian-style curry where roasted makhana puffs float in a rich onion-tomato gravy. This is comfort food with a clean-label upgrade — the makhana absorbs the spiced gravy while retaining a tender bite. Serve with steamed rice or warm rotis for a dinner that feels both indulgent and wholesome.',
    youtubeId: 'REPLACE_WITH_REAL_VIDEO_ID',
    time: '30 minutes',
    serves: '3',
    ingredients: [
      '2 cups Golden Deer Classic Roast makhana',
      '2 medium onions, finely chopped',
      '2 medium tomatoes, puréed',
      '1 tbsp ginger-garlic paste',
      '2 green chillies, slit',
      '½ cup fresh yoghurt, whisked',
      '2 tbsp ghee or cold-pressed oil',
      '1 tsp cumin seeds',
      '1 tsp turmeric powder',
      '1 tsp coriander powder',
      '½ tsp Kashmiri red chilli powder',
      '½ tsp garam masala',
      '¼ tsp asafoetida (hing)',
      '1 cup warm water',
      '2 tbsp fresh cream (optional, for richness)',
      'Fresh coriander for garnish',
      'Salt to taste',
    ],
    steps: [
      'Heat ghee in a deep pan over medium heat. Add cumin seeds and asafoetida — let them sizzle for 10 seconds.',
      'Add chopped onions and green chillies. Sauté until the onions turn deep golden brown, about 8 minutes. This is the flavour foundation — don\'t rush it.',
      'Add ginger-garlic paste and cook for 1 minute until fragrant.',
      'Add turmeric, coriander powder, and red chilli powder. Stir for 30 seconds until the spices bloom.',
      'Pour in the tomato purée. Cook on medium heat, stirring occasionally, until the mixture thickens and oil separates at the edges — about 5–6 minutes.',
      'Reduce heat to low. Add whisked yoghurt one spoonful at a time, stirring continuously to prevent curdling.',
      'Add warm water and salt. Bring to a gentle simmer.',
      'Gently stir in the Golden Deer Classic Roast makhana. Simmer for 3–4 minutes — the makhana will soften slightly while retaining their shape. Do not overcook or they will disintegrate.',
      'Sprinkle garam masala, add cream if using, and stir gently.',
      'Garnish with fresh coriander and serve hot. The makhana should be tender on the outside with a slight bite in the centre — like dumplings in a rich gravy.',
    ],
    loop: '/videos/recipes/makhana-curry.mp4',
    poster: '/videos/recipes/makhana-curry-poster.jpg',
  },
]
